repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-executables-have-shebangs
    -   id: check-byte-order-marker
    -   id: check-added-large-files
    -   id: check-symlinks
    -   id: detect-private-key
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v17.0.6'
    hooks:
    -   id: clang-format
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args:
        - --line-length=79
        - --preview

-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args:
        - --max-line-length=79
