#ifndef PICO_BOOTLOADER_HARDWARE_FLASH_STUB_H
#define PICO_BOOTLOADER_HARDWARE_FLASH_STUB_H

constexpr unsigned int FLASH_PAGE_SIZE{256};
constexpr unsigned int FLASH_SECTOR_SIZE{1024};

#endif  // PICO_BOOTLOADER_HARDWARE_FLASH_STUB_H
