#ifndef PICO_BOOTLOADER_HARDWARE_FLASH_STUB_H
#define PICO_BOOTLOADER_HARDWARE_FLASH_STUB_H

#define FLASH_PAGE_SIZE (1u << 8)
#define FLASH_SECTOR_SIZE (1u << 12)

#endif  // PICO_BOOTLOADER_HARDWARE_FLASH_STUB_H
