#ifndef PICO_BOOTLOADER_COMMON_DEFINITIONS_H
#define PICO_BOOTLOADER_COMMON_DEFINITIONS_H

#define PICO_UART uart0
#define PICO_UART_BAUD_RATE PICO_DEFAULT_UART_BAUD_RATE
enum { PICO_UART_TX_PIN = 16, PICO_UART_RX_PIN = 17 };

#endif
