name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ndreasndersson/picow-plant-moisture-sensor:latest
      volumes:
        - ${{ github.workspace }}:/project

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: ./build_and_combine.sh ${{env.BUILD_TYPE}}

    - name: Deploy
      uses: actions/upload-artifact@v4
      with:
        name: Release
        path: build/**/*.uf2

    - name: Test
      run: cmake --workflow --preset test
