name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    container:
      image: ndreasndersson/picow-plant-moisture-sensor:latest
      volumes:
        - ${{ github.workspace }}:/project

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: ./build_and_combine.sh ${{env.BUILD_TYPE}}
      - uses: actions/upload-artifact@v4
        with:
          name: Release
          path: build/**/*.uf2

  unittest:
    runs-on: ubuntu-latest
    container:
      image: ndreasndersson/picow-plant-moisture-sensor:latest
      volumes:
        - ${{ github.workspace }}:/project

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: cmake --workflow --preset test
