name: Unittest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ndreasndersson/picow-plant-moisture-sensor:latest
      volumes:
        - ${{ github.workspace }}:/project

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Test
      run: cmake --workflow --preset test
